/** Declaration file generated by dts-gen */

export interface ShinsOptions {
    // Allow css-style attributes in markdown
    attr?: boolean;
    // If true, missing files will trigger an exit(1)
    cli?: boolean;
    // Include custom CSS file with the naming convention `<theme|type>_overrides.css`
    customCss?: boolean;
    // If true, then HTML will be minified
    minify?: boolean;
    // if true, do not automatically convert links in text to anchor tags
    "no-links"?: boolean;
    // Bundle everything into a single HTML file
    inline?: boolean;
    // Setting to true turns off markdown sanitisation
    unsafe?: boolean;
    // Link to apply to the logo
    'logo-url'?: string;
    // Used to resolve relative paths for included files
    source?: string;
    // Path to a custom logo
    logo?: string;
    // The root location when the HTML files will be served up
    webRoot?: string;
}

export function render(inputStr: string, options: ShinsOptions, callback: Function): void;

export function srcDir(): string;
